<?php

namespace App\Charts;

use App\Models\HealthInformation;
use App\Models\Resident;
use ArielMejiaDev\LarapexCharts\LarapexChart;

class MedicalHistoryByPurokChart
{
    protected $chart;

    public function __construct(LarapexChart $chart)
    {
        $this->chart = $chart;
    }

    public function build(): \ArielMejiaDev\LarapexCharts\LineChart
    {
        $residentHealth = HealthInformation::with('resident')->get()->groupBy(['resident.purok', 'medical_history']);
        return $this->chart->lineChart()
            ->setTitle('Medical History By Purok')
            ->setSubtitle('Barangay Cabantian Davao City')
            ->addData('HPN (Hypertension)', [
                $residentHealth->has('Antonio Village') ? $residentHealth['Antonio Village']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Bacahoa Village') ? $residentHealth['Bacahoa Village']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Camelon Compound') ? $residentHealth['Camelon Compound']->firstWhere(fn($i, $k) => $k === 'Hypertension')->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 4') ? $residentHealth['CDE Phase 4']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 3') ? $residentHealth['CDE Phase 3']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 2') ? $residentHealth['CDE Phase 2']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 1') ? $residentHealth['CDE Phase 1']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Cecilia 1&2') ? $residentHealth['Cecilia 1&2']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Celerina Heights') ? $residentHealth['Celerina Heights']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes (Zone 11)') ? $residentHealth['Country Homes (Zone 11)']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes B1-B19') ? $residentHealth['Country Homes B1-B19']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('CHS #15 (B55-B47)') ? $residentHealth['CHS #15 (B55-B47)']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('CHS Purok (14 B36-B46)') ? $residentHealth['CHS Purok (14 B36-B46)']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes Sagingan') ? $residentHealth['Country Homes Sagingan']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('CHS #16 B56-62') ? $residentHealth['CHS #16 B56-62']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Country Ville Village') ? $residentHealth['Country Ville Village']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Chula Vista') ? $residentHealth['Chula Vista']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('D Achievers') ? $residentHealth['D Achievers']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Dacudao/Binoling (Amsay)') ? $residentHealth['Dacudao/Binoling (Amsay)']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 1-A (B14-20)') ? $residentHealth['Deca Homes Phase 1-A (B14-20)']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 2-A (B21-32)') ? $residentHealth['Deca Homes Phase 2-A (B21-32)']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 2-B(B2 33-41)') ? $residentHealth['Deca Homes Phase 2-B(B2 33-41)']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 1-B (B1-13)') ? $residentHealth['Deca Homes Phase 1-B (B1-13)']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Dela Peña Village') ? $residentHealth['Dela Peña Village']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Diho Phase 2') ? $residentHealth['Diho Phase 2']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Diho Phase 1') ? $residentHealth['Diho Phase 1']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Dragon Compound Purok 5') ? $residentHealth['Dragon Compound Purok 5']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes (Victors)') ? $residentHealth['Emilia Homes (Victors)']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 1A') ? $residentHealth['Emilia Homes Phase 1A']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Beside Emily') ? $residentHealth['Emilia Homes Beside Emily']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 1B') ? $residentHealth['Emilia Homes Phase 1B']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 2B') ? $residentHealth['Emilia Homes Phase 2B']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 2A') ? $residentHealth['Emilia Homes Phase 2A']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 3B') ? $residentHealth['Emilia Homes Phase 3B']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 3A') ? $residentHealth['Emilia Homes Phase 3A']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Green Orchard Village') ? $residentHealth['Green Orchard Village']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Greenland Phase 1') ? $residentHealth['Greenland Phase 1']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Greenland Phase 2') ? $residentHealth['Greenland Phase 2']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Holy Trinity Village') ? $residentHealth['Holy Trinity Village']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Laverna Hills Phase 3') ? $residentHealth['Laverna Hills Phase 3']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Laverna Hills Phase 1') ? $residentHealth['Laverna Hills Phase 1']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Pag-ibig Subdivision') ? $residentHealth['Pag-ibig Subdivision']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Pareñas Compound') ? $residentHealth['Pareñas Compound']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Precilla 1/2') ? $residentHealth['Precilla 1/2']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Pretige') ? $residentHealth['Pretige']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 32 Mountain View Village') ? $residentHealth['Purok 32 Mountain View Village']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 33 KM 11, San Roque') ? $residentHealth['Purok 33 KM 11, San Roque']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 34 Amakan') ? $residentHealth['Purok 34 Amakan']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 36 Arendain Compound') ? $residentHealth['Purok 36 Arendain Compound']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 36 Forestal') ? $residentHealth['Purok 36 Forestal']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 37 Forestal') ? $residentHealth['Purok 37 Forestal']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 39 Daitic Compound') ? $residentHealth['Purok 39 Daitic Compound']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Ramonena 2') ? $residentHealth['Ramonena 2']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Remedios Eights') ? $residentHealth['Remedios Eights']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Sialza Compound') ? $residentHealth['Sialza Compound']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Sta. Teresita Purok 1') ? $residentHealth['Sta. Teresita Purok 1']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Cab Elem. School') ? $residentHealth['Suraya Cab Elem. School']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 1') ? $residentHealth['Suraya Homes Phase 1']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 2A') ? $residentHealth['Suraya Homes Phase 2A']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 2B') ? $residentHealth['Suraya Homes Phase 2B']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('The Harmony Subdivision') ? $residentHealth['The Harmony Subdivision']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
                $residentHealth->has('Villa Park Subdivision') ? $residentHealth['Villa Park Subdivision']->firstWhere(fn($i, $k) => $k === 'Hypertension')?->count() ?? 0 : 0,
            ])
            ->addData('Diabetes (DM)', [
                $residentHealth->has('Antonio Village') ? $residentHealth['Antonio Village']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Bacahoa Village') ? $residentHealth['Bacahoa Village']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Camelon Compound') ? $residentHealth['Camelon Compound']->firstWhere(fn($i, $k) => $k === 'Diabetes')->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 4') ? $residentHealth['CDE Phase 4']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 3') ? $residentHealth['CDE Phase 3']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 2') ? $residentHealth['CDE Phase 2']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 1') ? $residentHealth['CDE Phase 1']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Cecilia 1&2') ? $residentHealth['Cecilia 1&2']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Celerina Heights') ? $residentHealth['Celerina Heights']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes (Zone 11)') ? $residentHealth['Country Homes (Zone 11)']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes B1-B19') ? $residentHealth['Country Homes B1-B19']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('CHS #15 (B55-B47)') ? $residentHealth['CHS #15 (B55-B47)']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('CHS Purok (14 B36-B46)') ? $residentHealth['CHS Purok (14 B36-B46)']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes Sagingan') ? $residentHealth['Country Homes Sagingan']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('CHS #16 B56-62') ? $residentHealth['CHS #16 B56-62']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Country Ville Village') ? $residentHealth['Country Ville Village']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Chula Vista') ? $residentHealth['Chula Vista']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('D Achievers') ? $residentHealth['D Achievers']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Dacudao/Binoling (Amsay)') ? $residentHealth['Dacudao/Binoling (Amsay)']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 1-A (B14-20)') ? $residentHealth['Deca Homes Phase 1-A (B14-20)']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 2-A (B21-32)') ? $residentHealth['Deca Homes Phase 2-A (B21-32)']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 2-B(B2 33-41)') ? $residentHealth['Deca Homes Phase 2-B(B2 33-41)']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 1-B (B1-13)') ? $residentHealth['Deca Homes Phase 1-B (B1-13)']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Dela Peña Village') ? $residentHealth['Dela Peña Village']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Diho Phase 2') ? $residentHealth['Diho Phase 2']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Diho Phase 1') ? $residentHealth['Diho Phase 1']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Dragon Compound Purok 5') ? $residentHealth['Dragon Compound Purok 5']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes (Victors)') ? $residentHealth['Emilia Homes (Victors)']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 1A') ? $residentHealth['Emilia Homes Phase 1A']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Beside Emily') ? $residentHealth['Emilia Homes Beside Emily']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 1B') ? $residentHealth['Emilia Homes Phase 1B']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 2B') ? $residentHealth['Emilia Homes Phase 2B']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 2A') ? $residentHealth['Emilia Homes Phase 2A']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 3B') ? $residentHealth['Emilia Homes Phase 3B']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 3A') ? $residentHealth['Emilia Homes Phase 3A']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Green Orchard Village') ? $residentHealth['Green Orchard Village']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Greenland Phase 1') ? $residentHealth['Greenland Phase 1']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Greenland Phase 2') ? $residentHealth['Greenland Phase 2']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Holy Trinity Village') ? $residentHealth['Holy Trinity Village']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Laverna Hills Phase 3') ? $residentHealth['Laverna Hills Phase 3']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Laverna Hills Phase 1') ? $residentHealth['Laverna Hills Phase 1']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Pag-ibig Subdivision') ? $residentHealth['Pag-ibig Subdivision']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Pareñas Compound') ? $residentHealth['Pareñas Compound']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Precilla 1/2') ? $residentHealth['Precilla 1/2']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Pretige') ? $residentHealth['Pretige']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 32 Mountain View Village') ? $residentHealth['Purok 32 Mountain View Village']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 33 KM 11, San Roque') ? $residentHealth['Purok 33 KM 11, San Roque']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 34 Amakan') ? $residentHealth['Purok 34 Amakan']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 36 Arendain Compound') ? $residentHealth['Purok 36 Arendain Compound']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 36 Forestal') ? $residentHealth['Purok 36 Forestal']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 37 Forestal') ? $residentHealth['Purok 37 Forestal']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 39 Daitic Compound') ? $residentHealth['Purok 39 Daitic Compound']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Ramonena 2') ? $residentHealth['Ramonena 2']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Remedios Eights') ? $residentHealth['Remedios Eights']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Sialza Compound') ? $residentHealth['Sialza Compound']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Sta. Teresita Purok 1') ? $residentHealth['Sta. Teresita Purok 1']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Cab Elem. School') ? $residentHealth['Suraya Cab Elem. School']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 1') ? $residentHealth['Suraya Homes Phase 1']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 2A') ? $residentHealth['Suraya Homes Phase 2A']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 2B') ? $residentHealth['Suraya Homes Phase 2B']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('The Harmony Subdivision') ? $residentHealth['The Harmony Subdivision']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
                $residentHealth->has('Villa Park Subdivision') ? $residentHealth['Villa Park Subdivision']->firstWhere(fn($i, $k) => $k === 'Diabetes')?->count() ?? 0 : 0,
            ])
            ->addData('Tuberculosis (TB)', [
                $residentHealth->has('Antonio Village') ? $residentHealth['Antonio Village']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Bacahoa Village') ? $residentHealth['Bacahoa Village']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Camelon Compound') ? $residentHealth['Camelon Compound']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 4') ? $residentHealth['CDE Phase 4']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 3') ? $residentHealth['CDE Phase 3']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 2') ? $residentHealth['CDE Phase 2']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 1') ? $residentHealth['CDE Phase 1']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Cecilia 1&2') ? $residentHealth['Cecilia 1&2']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Celerina Heights') ? $residentHealth['Celerina Heights']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes (Zone 11)') ? $residentHealth['Country Homes (Zone 11)']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes B1-B19') ? $residentHealth['Country Homes B1-B19']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('CHS #15 (B55-B47)') ? $residentHealth['CHS #15 (B55-B47)']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('CHS Purok (14 B36-B46)') ? $residentHealth['CHS Purok (14 B36-B46)']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes Sagingan') ? $residentHealth['Country Homes Sagingan']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('CHS #16 B56-62') ? $residentHealth['CHS #16 B56-62']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Country Ville Village') ? $residentHealth['Country Ville Village']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Chula Vista') ? $residentHealth['Chula Vista']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('D Achievers') ? $residentHealth['D Achievers']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Dacudao/Binoling (Amsay)') ? $residentHealth['Dacudao/Binoling (Amsay)']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 1-A (B14-20)') ? $residentHealth['Deca Homes Phase 1-A (B14-20)']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 2-A (B21-32)') ? $residentHealth['Deca Homes Phase 2-A (B21-32)']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 2-B(B2 33-41)') ? $residentHealth['Deca Homes Phase 2-B(B2 33-41)']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 1-B (B1-13)') ? $residentHealth['Deca Homes Phase 1-B (B1-13)']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Dela Peña Village') ? $residentHealth['Dela Peña Village']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Diho Phase 2') ? $residentHealth['Diho Phase 2']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Diho Phase 1') ? $residentHealth['Diho Phase 1']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Dragon Compound Purok 5') ? $residentHealth['Dragon Compound Purok 5']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes (Victors)') ? $residentHealth['Emilia Homes (Victors)']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 1A') ? $residentHealth['Emilia Homes Phase 1A']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Beside Emily') ? $residentHealth['Emilia Homes Beside Emily']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 1B') ? $residentHealth['Emilia Homes Phase 1B']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 2B') ? $residentHealth['Emilia Homes Phase 2B']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 2A') ? $residentHealth['Emilia Homes Phase 2A']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 3B') ? $residentHealth['Emilia Homes Phase 3B']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 3A') ? $residentHealth['Emilia Homes Phase 3A']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Green Orchard Village') ? $residentHealth['Green Orchard Village']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Greenland Phase 1') ? $residentHealth['Greenland Phase 1']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Greenland Phase 2') ? $residentHealth['Greenland Phase 2']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Holy Trinity Village') ? $residentHealth['Holy Trinity Village']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Laverna Hills Phase 3') ? $residentHealth['Laverna Hills Phase 3']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Laverna Hills Phase 1') ? $residentHealth['Laverna Hills Phase 1']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Pag-ibig Subdivision') ? $residentHealth['Pag-ibig Subdivision']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Pareñas Compound') ? $residentHealth['Pareñas Compound']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Precilla 1/2') ? $residentHealth['Precilla 1/2']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Pretige') ? $residentHealth['Pretige']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 32 Mountain View Village') ? $residentHealth['Purok 32 Mountain View Village']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 33 KM 11, San Roque') ? $residentHealth['Purok 33 KM 11, San Roque']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 34 Amakan') ? $residentHealth['Purok 34 Amakan']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 36 Arendain Compound') ? $residentHealth['Purok 36 Arendain Compound']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 36 Forestal') ? $residentHealth['Purok 36 Forestal']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 37 Forestal') ? $residentHealth['Purok 37 Forestal']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 39 Daitic Compound') ? $residentHealth['Purok 39 Daitic Compound']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Ramonena 2') ? $residentHealth['Ramonena 2']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Remedios Eights') ? $residentHealth['Remedios Eights']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Sialza Compound') ? $residentHealth['Sialza Compound']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Sta. Teresita Purok 1') ? $residentHealth['Sta. Teresita Purok 1']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Cab Elem. School') ? $residentHealth['Suraya Cab Elem. School']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 1') ? $residentHealth['Suraya Homes Phase 1']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 2A') ? $residentHealth['Suraya Homes Phase 2A']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 2B') ? $residentHealth['Suraya Homes Phase 2B']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('The Harmony Subdivision') ? $residentHealth['The Harmony Subdivision']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
                $residentHealth->has('Villa Park Subdivision') ? $residentHealth['Villa Park Subdivision']->firstWhere(fn($i, $k) => $k === 'Tuberculosis')?->count() ?? 0 : 0,
            ])
            ->addData('Surgery (S)', [
                $residentHealth->has('Antonio Village') ? $residentHealth['Antonio Village']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Bacahoa Village') ? $residentHealth['Bacahoa Village']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Camelon Compound') ? $residentHealth['Camelon Compound']->firstWhere(fn($i, $k) => $k === 'Surgery')->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 4') ? $residentHealth['CDE Phase 4']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 3') ? $residentHealth['CDE Phase 3']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 2') ? $residentHealth['CDE Phase 2']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('CDE Phase 1') ? $residentHealth['CDE Phase 1']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Cecilia 1&2') ? $residentHealth['Cecilia 1&2']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Celerina Heights') ? $residentHealth['Celerina Heights']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes (Zone 11)') ? $residentHealth['Country Homes (Zone 11)']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes B1-B19') ? $residentHealth['Country Homes B1-B19']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('CHS #15 (B55-B47)') ? $residentHealth['CHS #15 (B55-B47)']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('CHS Purok (14 B36-B46)') ? $residentHealth['CHS Purok (14 B36-B46)']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Country Homes Sagingan') ? $residentHealth['Country Homes Sagingan']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('CHS #16 B56-62') ? $residentHealth['CHS #16 B56-62']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Country Ville Village') ? $residentHealth['Country Ville Village']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Chula Vista') ? $residentHealth['Chula Vista']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('D Achievers') ? $residentHealth['D Achievers']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Dacudao/Binoling (Amsay)') ? $residentHealth['Dacudao/Binoling (Amsay)']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 1-A (B14-20)') ? $residentHealth['Deca Homes Phase 1-A (B14-20)']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 2-A (B21-32)') ? $residentHealth['Deca Homes Phase 2-A (B21-32)']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 2-B(B2 33-41)') ? $residentHealth['Deca Homes Phase 2-B(B2 33-41)']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Deca Homes Phase 1-B (B1-13)') ? $residentHealth['Deca Homes Phase 1-B (B1-13)']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Dela Peña Village') ? $residentHealth['Dela Peña Village']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Diho Phase 2') ? $residentHealth['Diho Phase 2']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Diho Phase 1') ? $residentHealth['Diho Phase 1']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Dragon Compound Purok 5') ? $residentHealth['Dragon Compound Purok 5']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes (Victors)') ? $residentHealth['Emilia Homes (Victors)']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 1A') ? $residentHealth['Emilia Homes Phase 1A']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Beside Emily') ? $residentHealth['Emilia Homes Beside Emily']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 1B') ? $residentHealth['Emilia Homes Phase 1B']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 2B') ? $residentHealth['Emilia Homes Phase 2B']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 2A') ? $residentHealth['Emilia Homes Phase 2A']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 3B') ? $residentHealth['Emilia Homes Phase 3B']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Emilia Homes Phase 3A') ? $residentHealth['Emilia Homes Phase 3A']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Green Orchard Village') ? $residentHealth['Green Orchard Village']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Greenland Phase 1') ? $residentHealth['Greenland Phase 1']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Greenland Phase 2') ? $residentHealth['Greenland Phase 2']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Holy Trinity Village') ? $residentHealth['Holy Trinity Village']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Laverna Hills Phase 3') ? $residentHealth['Laverna Hills Phase 3']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Laverna Hills Phase 1') ? $residentHealth['Laverna Hills Phase 1']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Pag-ibig Subdivision') ? $residentHealth['Pag-ibig Subdivision']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Pareñas Compound') ? $residentHealth['Pareñas Compound']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Precilla 1/2') ? $residentHealth['Precilla 1/2']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Pretige') ? $residentHealth['Pretige']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 32 Mountain View Village') ? $residentHealth['Purok 32 Mountain View Village']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 33 KM 11, San Roque') ? $residentHealth['Purok 33 KM 11, San Roque']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 34 Amakan') ? $residentHealth['Purok 34 Amakan']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 36 Arendain Compound') ? $residentHealth['Purok 36 Arendain Compound']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 36 Forestal') ? $residentHealth['Purok 36 Forestal']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 37 Forestal') ? $residentHealth['Purok 37 Forestal']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Purok 39 Daitic Compound') ? $residentHealth['Purok 39 Daitic Compound']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Ramonena 2') ? $residentHealth['Ramonena 2']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Remedios Eights') ? $residentHealth['Remedios Eights']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Sialza Compound') ? $residentHealth['Sialza Compound']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Sta. Teresita Purok 1') ? $residentHealth['Sta. Teresita Purok 1']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Cab Elem. School') ? $residentHealth['Suraya Cab Elem. School']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 1') ? $residentHealth['Suraya Homes Phase 1']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 2A') ? $residentHealth['Suraya Homes Phase 2A']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Suraya Homes Phase 2B') ? $residentHealth['Suraya Homes Phase 2B']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('The Harmony Subdivision') ? $residentHealth['The Harmony Subdivision']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
                $residentHealth->has('Villa Park Subdivision') ? $residentHealth['Villa Park Subdivision']->firstWhere(fn($i, $k) => $k === 'Surgery')?->count() ?? 0 : 0,
            ])
            ->setXAxis([
                'Antonio Village',
                'Bacahoa Village',
                'Camelon Compound',
                'CDE Phase 4',
                'CDE Phase 3',
                'CDE Phase 2',
                'CDE Phase 1',
                'Cecilia 1&2',
                'Celerina Heights',
                'Country Homes (Zone 11)',
                'Country Homes B1-B19',
                'CHS #15 (B55-B47)',
                'CHS Purok (14 B36-B46)',
                'Country Homes Sagingan',
                'CHS #16 B56-62',
                'Country Ville Village',
                'Chula Vista',
                'D Achievers',
                'Dacudao/Binoling (Amsay)',
                'Deca Homes Phase 1-A (B14-20)',
                'Deca Homes Phase 2-A (B21-32)',
                'Deca Homes Phase 2-B(B2 33-41)',
                'Deca Homes Phase 1-B (B1-13)',
                'Dela Peña Village',
                'Diho Phase 2',
                'Diho Phase 1',
                'Dragon Compound Purok 5',
                'Emilia Homes (Victors)',
                'Emilia Homes Phase 1A',
                'Emilia Homes Beside Emily',
                'Emilia Homes Phase 1B',
                'Emilia Homes Phase 2B',
                'Emilia Homes Phase 2A',
                'Emilia Homes Phase 3B',
                'Emilia Homes Phase 3A',
                'Green Orchard Village',
                'Greenland Phase 1',
                'Greenland Phase 2',
                'Holy Trinity Village',
                'Laverna Hills Phase 3',
                'Laverna Hills Phase 1',
                'Pag-ibig Subdivision',
                'Pareñas Compound',
                'Precilla 1/2',
                'Pretige',
                'Purok 32 Mountain View Village',
                'Purok 33 KM 11, San Roque',
                'Purok 34 Amakan',
                'Purok 36 Arendain Compound',
                'Purok 36 Forestal',
                'Purok 37 Forestal',
                'Purok 39 Daitic Compound',
                'Ramonena 2',
                'Remedios Eights',
                'Sialza Compound',
                'Sta. Teresita Purok 1',
                'Suraya Cab Elem. School',
                'Suraya Homes Phase 1',
                'Suraya Homes Phase 2A',
                'Suraya Homes Phase 2B',
                'The Harmony Subdivision',
                'Villa Park Subdivision'
            ]);
    }
}
